name: ciclar_mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  get_it: ^7.7.0
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  sqflite: ^2.3.3+1
  path: ^1.9.0
  internet_connection_checker: ^2.0.0
  go_router: ^14.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  build_runner: ^2.4.12
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
